### ISSUE TITLE
Cannot find serializer implementation for mesh version [MeshSerializer_v1.8]

### ISSUE THREAD

**Issue by vido89** [lamogui/ogre_blender_importer#1] opened 2016-09-20 15:22 UTC
Blender 2.76

```
Read new prefs: /home/slobodan/.config/blender/2.76/config/userpref.blend
Import error: No module named 'OgreMeshSerializer' manual compilation
Import error: No module named 'OgreMeshSerializerImpl' manual compilation
Import error: No module named 'OgreSerializer' manual compilation
Import error: No module named 'OgreStringUtils' manual compilation
Import error: No module named 'OgreVertexBuffer' manual compilation
Import error: No module named 'OgreHardwareBuffer' manual compilation
Import error: No module named 'OgreHardwareBuffer' manual compilation
Import error: No module named 'OgreStringUtils' manual compilation
Import error: No module named 'OgreSubMesh' manual compilation
Import error: No module named 'OgreVertexIndexData' manual compilation
Import error: No module named 'OgreVertexBuffer' manual compilation
Import error: No module named 'OgreHardwareBuffer' manual compilation
Import error: No module named 'OgreSerializer' manual compilation
Import error: No module named 'OgreStringUtils' manual compilation
Import error: No module named 'OgreSkeletonFileFormat' manual compilation
Import error: No module named 'OgreStringUtils' manual compilation
    WM_OT_context_toggle
    WM_OT_context_toggle_enum
    WM_OT_context_cycle_int
    WM_OT_context_cycle_enum
    WM_OT_context_cycle_array
    WM_OT_context_menu_enum
[MeshSerializer_v1.8]
Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/ogre_blender_importer/__init__.py", line 70, in execute
    meshserializer.importMesh(meshfile);
  File "OgreMeshSerializer.py", line 103, in importMesh
ValueError: Cannot find serializer implementation for mesh version [MeshSerializer_v1.8]

location: <unknown location>:-1

location: <unknown location>:-1

```

**Comment by lamogui** [comment] 2016-09-20 15:44
Yeah the only supported version for now is Ogre 1.10 Maybe if I have time this night I will add the support for 1.8. Can you send me your file for testing ?

**Comment by lamogui** [comment] 2016-09-20 19:04
I have done something for this, as long as your mesh doesn't have lod or multi submesh this should work

**Comment by vido89** [comment] 2016-09-21 15:10
Hey tnx I did converted my mesh to 1.10 but stil Im getting this error

```
$ blender
connect failed: No such file or directory
Read new prefs: /home/slobodan/.config/blender/2.76/config/userpref.blend
Import error: No module named 'OgreMeshSerializer' manual compilation
Import error: No module named 'OgreMeshSerializerImpl' manual compilation
Import error: No module named 'OgreSerializer' manual compilation
Import error: No module named 'OgreStringUtils' manual compilation
Import error: No module named 'OgreVertexBuffer' manual compilation
Import error: No module named 'OgreHardwareBuffer' manual compilation
Import error: No module named 'OgreHardwareBuffer' manual compilation
Import error: No module named 'OgreStringUtils' manual compilation
Import error: No module named 'OgreSubMesh' manual compilation
Import error: No module named 'OgreVertexIndexData' manual compilation
Import error: No module named 'OgreVertexBuffer' manual compilation
Import error: No module named 'OgreHardwareBuffer' manual compilation
Import error: No module named 'OgreSerializer' manual compilation
Import error: No module named 'OgreStringUtils' manual compilation
Import error: No module named 'OgreSkeletonFileFormat' manual compilation
Import error: No module named 'OgreStringUtils' manual compilation
Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/ogre_blender_importer-master/__init__.py", line 70, in execute
    meshserializer.importMesh(meshfile);
  File "OgreMeshSerializer.py", line 91, in importMesh
  File "OgreSerializer.py", line 61, in _determineEndianness
ValueError: OgreSerializer._determineEndianness(self,stream): Header chunk didn't match either endian: Corrupted stream?

location: <unknown location>:-1

location: <unknown location>:-1
```

and this

```
M_MESH
Skeletally animated: False
  M_GEOMETRY
    Vertex count: 24
    streamID 0x5100 (offset: 0x31)
    M_GEOMETRY_VERTEX_DECLARATION
      M_GEOMETRY_VERTEX_ELEMENT
        source: 0
        type: VET_FLOAT3
        semantic: VES_POSITION
        offset: 0
        index: 0
Corrupted chunk detected ! Chunk ID: 20752
      M_GEOMETRY_VERTEX_ELEMENT
        source: 0
        type: VET_FLOAT3
        semantic: VES_NORMAL
        offset: 12
        index: 0
Corrupted chunk detected ! Chunk ID: 20992
    streamID 0x5200 (offset: 0x57)
    M_GEOMETRY_VERTEX_BUFFER
      bind index: 0
      vertex size: 24
      buffered 576 elements
Corrupted chunk detected !
    streamID 0x4000 (offset: 0x2a7)
Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/ogre_blender_importer-master/__init__.py", line 70, in execute
    meshserializer.importMesh(meshfile);
  File "OgreMeshSerializer.py", line 109, in importMesh
  File "OgreMeshSerializerImpl.py", line 480, in importMesh
  File "OgreMeshSerializerImpl.py", line 415, in _readMesh
  File "OgreMeshSerializerImpl.py", line 159, in _readGeometry
AssertionError

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by lamogui** [comment] 2016-09-21 15:26
@vido89 I will really need your file to see what's going on can you also indicate the operating system, blender version and what did you use to convert the mesh (you can also try with the orginal mesh).

From which mesh version correspond the error (the 1.8 or the 1.10 ?)

**Comment by vido89** [comment] 2016-09-21 15:38
Im using ubuntu 16.04

```
blender -v
Blender 2.76 (sub 0)
```

[Test.zip](https://github.com/lamogui/ogre_blender_importer/files/485430/Test.zip)
sorry about that first error is 1.8 and second is converterd 1.10

**Comment by lamogui** [comment] 2016-09-21 18:45
I couldn't reproduce the first error, but I have the second error on both files

**Comment by lamogui** [comment] 2016-09-21 20:14
@vido89 Ok I pushed a fix. normals import are not supported yet. 
Please close the issue if it's ok on your side.

**Comment by vido89** [comment] 2016-09-21 20:19
Its ok now tnx for fix I really appreciate your work, cheers!

**Closed as completed** 2016-09-21 20:19 UTC
